accounts/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, custom_logout

app_name = 'accounts'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.home, name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('verify_otp/<int:user_profile_id>/', views.verify_otp, name='verify_otp'),
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('register/', views.register, name='register'),
]

escrow/urls.py
from django.urls import path
from . import views

app_name = 'escrow'

urlpatterns = [
    path('ecsrow_dashboard/', views.escrow_dashboard, name='escrow_dashboard'),
    path('create_escrow/', views.create_escrow, name='create_escrow'),
    path('transaction/<int:pk>/', views.escrow_details, name='escrow_details' ),
    path('escrow_list/', views.escrow_list, name='escrow_list'),
    path('user-search/', views.user_search, name='user-search'),
]

escrowtz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#remove later for base test only
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('escrow.urls', namespace='escrow')),
    path("select2/", include("django_select2.urls")),
    #for testing only the base
    path('base/', views.base_view, name='base'),
   
]



# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import random, string
from datetime import datetime, timedelta
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_verified = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=15)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    user_name = models.CharField(max_length=60, unique=True)
    otp = models.CharField(max_length=6, blank=True)
    email = models.EmailField(null=True, blank=True)
    address = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.phone_number} {self.user_name} {self.email} {self.address} {self.created_at} {self.otp} {self.is_verified}'

def generate_otp():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=6))

class OTP(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='otps')
    otp = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def is_valid(self):
        return timezone.now() < self.expires_at

    def __str__(self):
        return f'{self.otp} {self.created_at} {self.expires_at}'

@receiver(post_save, sender=UserProfile)
def send_otp(sender, instance, created, **kwargs):
    if created:
        otp_code = generate_otp()
        instance.otp = otp_code
        instance.save()
        OTP.objects.create(user_profile=instance, otp=otp_code, expires_at=timezone.now() + timedelta(minutes=5))

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, OTP
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
from datetime import datetime, timedelta
from django.utils import timezone
import random, string

#OTP generation
def generate_otp():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=6))

#Return error message for incorect phone number format
phone_regex = RegexValidator(regex=r'^\+\d{12}$', message="Phone number must be entered in the format: '+255123456789'.")


#user registration form
class UserRegistrationForm(forms.ModelForm):
    user_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'User Name'}),
    )
    phone_number = forms.CharField(
        max_length=15,
        validators=[phone_regex],
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': '+255123456789'}),
    )
    password = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )  
    password_confirm = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
    )
    class Meta:
        model = UserProfile
        fields = ['user_name', 'phone_number', 'password', 'password_confirm']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match')

    def save(self, commit=True):
        user_profile = super().save(commit=False)
        user = User.objects.create_user(username=self.cleaned_data['user_name'], password=self.cleaned_data['password'])
        user_profile.user = user
        if commit:
            user_profile.save()
            otp_code = generate_otp()
            OTP.objects.create(user_profile=user_profile, otp=otp_code, expires_at=timezone.now() + timedelta(minutes=5))
        return user_profile


#OTP verification
class OTPVerificationForm(forms.Form):
    otp = forms.CharField(
        max_length=6,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'OTP'}),
    )

    def __init__(self, *args, **kwargs):
        self.user_profile = kwargs.pop('user_profile')
        super().__init__(*args, **kwargs)

    def clean_otp(self):
        otp = self.cleaned_data['otp']
        otp_instance = OTP.objects.filter(user_profile=self.user_profile, otp=otp).first()
        if not otp_instance or not otp_instance.is_valid():
            raise forms.ValidationError("Invalid or expired OTP")
        return otp


#Log in form
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'User Name'}),
    )
    password = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )


#user proflie update
class UserUpdateForm(forms.ModelForm):
    user_name = forms.CharField(
        required=True,
        disabled=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'User Name'}),
    )
    
    phone_number = forms.CharField(max_length=15, disabled=True)
    
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
    )
    
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
    )
    address = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
    )
    
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'first_name', 'last_name', 'user_name', 'email', 'address']
     
        #To Ensure username and phone number are not changed
    def clean(self):
        cleaned_data = super().clean()
        if 'user_name' in cleaned_data:
            cleaned_data.pop('user_name')
        if 'phone_number' in cleaned_data:
            cleaned_data.pop('phone_number')

    #save the form
    def save(self, commit=True):
        user_profile = super().save(commit=False)
        user = user_profile.user
        user_profile.save()
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
            user.save()
        if commit:
            user_profile.save()
        return user_profile

class PasswordUpdate(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New Password'}),
    )
    password_confirm = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm New Password'}),
    )
    
    class Meta:
        model = UserProfile
        fields = ['password', 'password_confirm']
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match')
    
    #save the form
    def save(self, commit=True):
        user_profile = super().save(commit=False)
        user = user_profile.user
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
            user.save()
        if commit:
            user_profile.save()
        return user_profile
    

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from .forms import UserRegistrationForm, OTPVerificationForm, UserUpdateForm, LoginForm, PasswordUpdate
from .models import UserProfile, OTP
from django.db import IntegrityError
from datetime import datetime, timedelta
from django.urls import reverse

#Home page request
def home(request):
    return render(request, 'accounts/home.html')


#User registration 
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            try:
                user_profile = form.save()
                login(request, user_profile.user)
                return redirect('accounts:verify_otp', user_profile_id=user_profile.id)
            except IntegrityError:
                return form.add_error('user_name', 'Username already exists. Please choose another one.')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

#OTP verification
def verify_otp(request, user_profile_id):
    user_profile = get_object_or_404(UserProfile, id=user_profile_id)
    otp = user_profile.otp
    if request.method == 'POST':
        form = OTPVerificationForm(request.POST, user_profile=user_profile)
        if form.is_valid():
            entered_otp = form.cleaned_data.get('otp')
            if otp == entered_otp and OTP.objects.filter(user_profile=user_profile, otp=otp).first().is_valid():
                user_profile.is_verified = True
                user_profile.save()
                return redirect('accounts:dashboard')
            else:
                form.add_error('otp', 'Invalid OTP or OTP has expired.')
    else:
        form = OTPVerificationForm(user_profile=user_profile)
    return render(request, 'accounts/verify_otp.html', {'otp': otp, 'form': form})


#Registared user login
class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'



@login_required
#Update user profile
def profile_update(request):
    user_profile = request.user.userprofile
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:dashboard')
    else:
        form = UserUpdateForm(instance=user_profile)
    return render(request, 'accounts/profile_update.html', {'form': form})

#Password update
def password_reset(request):
    user_profile = request.user.userprofile
    if request.method == 'POST':
        form = PasswordUpdate(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:password_reset_confirm')
    else:
        form = PasswordUpdate(request.POST, instance=user_profile)
    return render(request, 'accounts/password_reset.html', {'form':form})
        

@login_required
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def password_reset_confirm(request):
    return render(request, 'accounts/password_reset_confirm.html')

def custom_logout(request):
    logout(request)
    return render(request, 'accounts/home.html', {})

accounts/templates/accounts/dashboard.html
<!-- accounts/templates/accounts/dashboard.html -->

{% extends 'escrowtz/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<h2>Welcome to user dashboard, {{user.username}} </h2>
<p>Here you can update your profile, create new transration and more</p>
<div class='container'>
    <a href="{% url 'accounts:profile_update' %}" class='btn'>Update Profile</a>
    <a href="{% url 'escrow:escrow_dashboard' %}" class='btn'>My Escrow</a>
    <a href="{% url 'accounts:password_reset' %}" class='btn'>Reset Password</a>
    <a href="{% url 'accounts:logout' %}" class='btn'>Logout</a>
</div>

{% endblock %}

accounts/templates/accounts/home.html
<!-- accounts/templates/accounts/home.html -->

{% extends 'escrowtz/base.html' %}

{% load static %}

{% block title %}EscrowTZ{% endblock %}

{% block content %}
<div class='main-content'>
    <h3>Secure Your Transactions with Confidence</h3>
    <h1>WELCOME TO EscrowTZ</h1>
    <p> At EscrowTZ, we provide a secure, decentralized,
        and cost-effective escrow service to ensure your 
        transactions are smooth and trustworthy. Whether you're buying, 
        selling, or exchanging goods and services, our platform guarantees 
        peace of mind for both parties involved..
    </p>
    <div class='container'>
        <a href="{% url 'accounts:register' %}" class='btn'>Start the Journey!</a>
        <a href="{% url 'accounts:login' %}" class='btn'>Are you on the road?</a>
    </div>
    <div>
        <h1>HOW DOES IT WORKS: 5 Key Steps</h1>
        <p>
            At EscrowTZ, we make the process of securing your transactions simple and efficient. 
            Our platform is designed to protect both buyers and sellers, ensuring that funds are 
            handled safely and that all conditions of the transaction are met before any money changes 
            hands. Here’s a step-by-step guide to how our escrow service works:
        </p>
    </div>
    <div>
        <h2 class='agree'> 1. Agreement and Escrow Account Setup </h2>
        <div class='img'>
            <img src="{% static 'accounts/agreement.png' %}" alt="Agreement">
        </div>
        <p>
            <b>Initial Agreement:</b> The buyer and seller discuss and agree on the 
            terms of the transaction, including the price, delivery timeline, and 
            specific conditions that must be met.<br>
            <b>Account Creation:</b> An escrow account is created on the EscrowTZ
            platform. This account will hold the funds securely until all 
            conditions of the agreement are met.<br>
            <b>Escrow Instructions:</b> Both parties provide detailed instructions to EscrowTZ,
            ensuring clear understanding and expectations
        </p>
        
        <h2> 2. Depositing Funds </h2>
        <div class='img'>
            <img src="{% static 'accounts/money_transfer.png' %}" alt="Money Transfer">
        </div>
        <p>
            <b>Buyer Deposit:</b> The buyer deposits the agreed-upon funds into the escrow account
            using a secure payment method. EscrowTZ supports various payment options for convenience.<br>
            <b>Confirmation:</b> EscrowTZ verifies the receipt of funds and notifies both parties.
            This step ensures that the funds are available and reserved for the transaction, 
            providing assurance to the seller.
        </p>

        <h2> 3. Fulfillment of Conditions</h2>
        <div class='img'>
            <img src="{% static 'accounts/fullfilment.png' %}" alt="Fulfillment">
        </div>
        <p>
            <b>Seller Delivers:</b> The seller fulfills their part of the agreement by delivering
            the goods or services to the buyer. This might include shipping a product, 
            providing a service, or delivering digital assets.<br>
            <b>Inspection Period:</b> The buyer is given a specified period to inspect the goods or 
            services. During this time, the buyer checks that all conditions and quality 
            standards are met as per the agreement.
        </p>

        <h2> 4. Verification and Approval</h2>
        <div class='img'>
            <img src="{% static 'accounts/verification.png' %}" alt="Verification">
        </div>
        <p>
        </b>
            <b>Buyer Approval:</b> If the buyer is satisfied with the delivery, they inform EscrowTZ
            to release the funds. This step confirms that the transaction terms have been met.<br>
            <b>Dispute Resolution:</b> If there are any issues or disputes, EscrowTZ steps in to mediate.
            The escrow agent reviews the terms, conditions, and evidence provided by both parties 
            to resolve the dispute fairly and impartially.
        </p>

        <h2> 5. Release of Funds</h2>
        <div class='img'>
            <img src="{% static 'accounts/release_fund.png' %}" alt="Release">
        </div>
        <p>
            <b>Funds Release:</b> Once the buyer’s approval is received, EscrowTZ releases the funds to the seller’s 
            account. This ensures that the seller is paid promptly for fulfilling their part of the agreement.<br>
            <b>Transaction Closure:</b> Both parties receive a confirmation of the completed transaction from EscrowTZ. 
            This includes a detailed record of the transaction for future reference.
        </p>
    </div>


    <hr class='bottom-line'>

    <h1>Features of EscrowTZ</h1>

    <div class='features'>
        <div class='img-section'>
            <div class='img'>
                <img src="{% static 'accounts/blockchain.png' %}" alt="Blockchain">
            </div>
            <h2>Decentralization</h2>
            <p>Built on a decentralized platform to ensure transparency and reliability.</p>
        </div>
        <div class='img-section'>
            <div class='img'>
                <img width='100px' height='100px' src="{% static 'accounts/secure.png' %}" alt="Security">
            </div>
            <h2>Security</h2>
            <p>Advanced encryption and security protocols to protect your funds and data.</p>
        </div>
        <div class='img-section'>
            <div class='img'>
                <img width='100px' height='100px' src="{% static 'accounts/cost_effective.png' %}" alt="Cost Effective">
            </div>
            <h2>Cost Effective</h2>
            <p>Competitive fees that save you money on every transaction.</p>
        </div>
        <div class='img-section'>
            <div class='img'>
                <img width='100px' height='100px' src="{% static 'accounts/dashboard.png' %}" alt="Dashboard">
            </div>
            <h2>User-Friendly Dashboard</h2>
            <p>Intuitive dashboard to manage and track all your transactions seamlessly.</p>
        </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
<!-- accounts/templates/accounts/login.html -->

{% extends 'escrowtz/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class='container'>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class='form-group'>
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors }}
        <div>
        <div class='form-group'>
            {{ form.password.label_tag }}
            {{ form.password }}
            {{ form.password.errors }}
        <div>
        <button type="submit">Login</button>
    </form>
    <h2>Don't have an account?</h2>
    <a href="{% url 'accounts:register' %}" class='btn'>Register</a>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
<!-- accounts/templates/accounts/logout.html -->
{% extends 'escrowtz/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}

<div class='container'>
<h2>Loged Out</h2>
<p> You have successfull <strong>loged out</strong>. See you soon!</p>
<a href="{% url 'accounts:home' %}" class='btn'>Return Home</a>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
<!-- accounts/templates/accounts/password_reset.html -->
 
{% extends 'escrowtz/base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}

<div class='container'>
    <h2>Reset your Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
            {{ form.password.errors }}
        </div>
        <div class="form-group">
            {{ form.password_confirm.label_tag }}
            {{ form.password_confirm }}
            {{ form.password_confirm.errors }}
        </div>
        <button type="submit">Reset</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
<!-- accounts/templates/accounts/password_reset_confirm.html -->
{% extends 'escrowtz/base.html' %}

{% block title %}Password Reset Confirm{% endblock %}

{% block content %}

<div class='container'>
<h2>Password Saved</h2>
<p>You have successfull updated your <strong>password</strong>. Keep it safe</p>
<a href="{% url 'accounts:dashboard' %}" class='btn'>Dashboard</a>
</div>

{% endblock %}

accounts/templates/accounts/profile_update.html
<!-- accounts/templates/accounts/profile_update.html -->
 
{% extends 'escrowtz/base.html' %}

{% block title %}Profile Update{% endblock %}

{% block content %}

<div class='container'>
    <h2>Update your Profile</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.phone_number.label_tag }}
            {{ form.phone_number }}
            {{ form.phone_number.errors }}
        </div>
        <div class="form-group">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="form-group">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="form-group">
            {{ form.user_name.label_tag }}
            {{ form.user_name }}
            {{ form.user_name.errors }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            {{ form.address.label_tag }}
            {{ form.address }}
            {{ form.address.errors }}
        </div>
        <button type="submit">Update</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/register.html
<!-- accounts/templates/accounts/register.html -->
 
{% extends 'escrowtz/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

<div class='container'>
    <h2>Welcome to Registrations</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class='form-group'>
            {{ form.user_name.label_tag }}
            {{ form.user_name }}
            {{ form.user_name.errors }}
        <div>
        <div class='form-group'>
            {{ form.phone_number.label_tag }}
            {{ form.phone_number }}
            {{ form.phone_number.errors }}
        <div>
        <div class='form-group'>
            {{ form.password.label_tag }}
            {{ form.password }}
            {{ form.password.errors }}
        <div>
        <div class='form-group'>
            {{ form.password_confirm.label_tag }}
            {{ form.password_confirm }}
            {{ form.password_confirm.errors }}
        <div>
        <button type="submit">Register</button>
    </form>
    <h2> Already having an accont?</h2>
    <a href="{% url 'accounts:login' %}" class='btn'>Login</a>
</div>

{% endblock %}

accounts/templates/accounts/verify_otp.html
<!-- accounts/templates/accounts/verify_otp.html -->

{% extends 'escrowtz/base.html' %}

{% block title %}Verify OTP{% endblock %}

{% block content %}

<div class='container'>
    <h2>Verify OTP: {{ otp }} </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class='form-group'>
            {{ form.otp.label_tag }}
            {{ form.otp}}
            {{ form.otp.errors }}
        <div>
        <button type="submit">Verify OTP</button>
    </form>
</div>

{% endblock %}