accounts/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, custom_logout

app_name = 'accounts'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.home, name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('verify_otp/<int:user_profile_id>/', views.verify_otp, name='verify_otp'),
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('register/', views.register, name='register'),
]

escrow/urls.py
from django.urls import path
from . import views

app_name = 'escrow'

urlpatterns = [
    path('ecsrow_dashboard/', views.escrow_dashboard, name='escrow_dashboard'),
    path('create_escrow/', views.create_escrow, name='create_escrow'),
    path('transaction/<int:pk>/', views.escrow_details, name='escrow_details' ),
    path('escrow_list/', views.escrow_list, name='escrow_list'),
    path('user-search/', views.user_search, name='user-search'),
]

escrowtz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#remove later for base test only
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('escrow.urls', namespace='escrow')),
    path("select2/", include("django_select2.urls")),
    #for testing only the base
    path('base/', views.base_view, name='base'),
   
]



# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <tittle>{% block tittle %}EscrowTZ{% endblock %}</tittle>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <span>EscrowTZ</span>
        <span class="nav-toggle" onclick="toggleNav()">☰</span>
        <nav id="jnav-links">
            <a href="{% url 'escrow:home' %}">Home</a>
            <a href="{% url 'escrow:about' %}">About</a>
            <a href="{% url 'escrow:contact' %}">Contact</a>
            <a href="{% url 'escrow:terms_and_conditions' %}">Terms & Conditions</a>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p class="footer">&copy; 2024 EscrowTZ</p>
    </footer>
    <script>
        function toggleNav() {
            var nav = document.getElementById("nav-links");
            if (nav.style.display === "block" || nav.style.display === "") {
                nav.style.display = "none";
            } else {
                nav.style.display = "block";
            }
        }
    </script>
</body>
</html>