accounts/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, custom_logout

app_name = 'accounts'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.home, name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('verify_otp/<int:user_profile_id>/', views.verify_otp, name='verify_otp'),
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('register/', views.register, name='register'),
]

escrow/urls.py
from django.urls import path
from . import views

app_name = 'escrow'

urlpatterns = [
    path('ecsrow_dashboard/', views.escrow_dashboard, name='escrow_dashboard'),
    path('create_escrow/', views.create_escrow, name='create_escrow'),
    path('transaction/<int:pk>/', views.escrow_details, name='escrow_details' ),
    path('escrow_list/', views.escrow_list, name='escrow_list'),
    path('user-search/', views.user_search, name='user-search'),
]

escrowtz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#remove later for base test only
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('escrow.urls', namespace='escrow')),
    path("select2/", include("django_select2.urls")),
    #for testing only the base
    path('base/', views.base_view, name='base'),
   
]



# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escrowtz/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound

def base_view(request):
    return render(request, 'escrowtz/base.html')

templates/escrowtz/base.html
<!-- project/templates/project/base.html -->

<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    
</head>
<body>
    <header>
        <a href="{% url 'accounts:home' %}" style='text-decoration:none' class='name'>EscrowTZ</a>
        <span class="nav-toggle" onclick="toggleNav()">☰</span>
        <nav id="nav-links">
            
            <a href="{% url 'accounts:home' %}">Home</a>
            <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:register' %}">Register</a>
        </nav>
    </header>
    <main>
        {% block content %}
    
        {% endblock %}
    </main>
    <footer>
        <p class="footer">&copy; 2024 EscrowTZ <br> Your Trusted Partner in Secure Transactions</p>
    </footer>
    <script src="{% static 'scripts/script.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.django-select2').select2();
        });
    </script>

</body>
</html>